# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tink/proto/aes_cmac_prf.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'tink/proto/aes_cmac_prf.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dtink/proto/aes_cmac_prf.proto\x12\x12google.crypto.tink\"3\n\rAesCmacPrfKey\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x11\n\tkey_value\x18\x02 \x01(\x0c\"8\n\x13\x41\x65sCmacPrfKeyFormat\x12\x0f\n\x07version\x18\x02 \x01(\r\x12\x10\n\x08key_size\x18\x01 \x01(\rB_\n\x1c\x63om.google.crypto.tink.protoP\x01Z=github.com/tink-crypto/tink-go/v2/proto/aes_cmac_prf_go_protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tink.proto.aes_cmac_prf_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\034com.google.crypto.tink.protoP\001Z=github.com/tink-crypto/tink-go/v2/proto/aes_cmac_prf_go_proto'
  _globals['_AESCMACPRFKEY']._serialized_start=53
  _globals['_AESCMACPRFKEY']._serialized_end=104
  _globals['_AESCMACPRFKEYFORMAT']._serialized_start=106
  _globals['_AESCMACPRFKEYFORMAT']._serialized_end=162
# @@protoc_insertion_point(module_scope)
