# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tink/proto/kms_envelope.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'tink/proto/kms_envelope.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tink.proto import tink_pb2 as tink_dot_proto_dot_tink__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dtink/proto/kms_envelope.proto\x12\x12google.crypto.tink\x1a\x15tink/proto/tink.proto\"b\n\x18KmsEnvelopeAeadKeyFormat\x12\x0f\n\x07kek_uri\x18\x01 \x01(\t\x12\x35\n\x0c\x64\x65k_template\x18\x02 \x01(\x0b\x32\x1f.google.crypto.tink.KeyTemplate\"c\n\x12KmsEnvelopeAeadKey\x12\x0f\n\x07version\x18\x01 \x01(\r\x12<\n\x06params\x18\x02 \x01(\x0b\x32,.google.crypto.tink.KmsEnvelopeAeadKeyFormatB_\n\x1c\x63om.google.crypto.tink.protoP\x01Z=github.com/tink-crypto/tink-go/v2/proto/kms_envelope_go_protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tink.proto.kms_envelope_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\034com.google.crypto.tink.protoP\001Z=github.com/tink-crypto/tink-go/v2/proto/kms_envelope_go_proto'
  _globals['_KMSENVELOPEAEADKEYFORMAT']._serialized_start=76
  _globals['_KMSENVELOPEAEADKEYFORMAT']._serialized_end=174
  _globals['_KMSENVELOPEAEADKEY']._serialized_start=176
  _globals['_KMSENVELOPEAEADKEY']._serialized_end=275
# @@protoc_insertion_point(module_scope)
